lsst-sqre/neophile

docs/config.rst
docs/index.rst

Add documentation for using Dependabot, neophile, and WhiteSource
Renovate, and when each of the three should be used.

[DM-26009] Document how to enable updates for a package

---

docs/config.rst

Stick with a weekly cadence for all version upgrade monitoring.

Document scheduling Renovate changes weekly

---

CHANGELOG.rst
requirements/dev.txt
src/neophile/analysis/kustomize.py
src/neophile/scanner/kustomize.py
src/neophile/update/kustomize.py
tests/analysis/kustomize_test.py
tests/data/kubernetes/sqrbot-jr/kustomization.yaml
tests/scanner/kustomize_test.py
tests/update/kustomize_test.py

- Support full URLs like we use for Argo CD for Kustomize external resources
- Pass the parsed URL information down through the update so that we don't have to repeat work

[DM-26507] Support full URLs for Kustomize external resources

---

.github/workflows/ci.yaml
scripts/docker-tag.sh

Only build Docker images for tagged releases and ticket branches.
Use the official Docker actions, and use a script to determine the
Docker tag.
Use the pre-commit action instead of running pre-commit with tox
to get the benefit of pre-commit environment caching.

[DM-29123] Update Docker and pre-commit CI configuration

---

CHANGELOG.rst
src/neophile/pr.py
tests/cli_test.py
tests/pr_test.py
tests/processor_test.py

The code to enable auto-merge was using the wrong field from the
return value of creating a new PR.  Use the number field instead
of the id field to get the PR number.
Update pinned dependencies.

[DM-32423] Fix enabling of auto-merge for new PR

---

src/neophile/analysis/base.py
src/neophile/analysis/helm.py
src/neophile/analysis/kustomize.py
src/neophile/analysis/pre_commit.py
src/neophile/analysis/python.py
src/neophile/cli.py
src/neophile/factory.py
src/neophile/inventory/github.py
src/neophile/inventory/helm.py
src/neophile/inventory/version.py
src/neophile/pr.py
src/neophile/processor.py
src/neophile/repository.py
src/neophile/scanner/helm.py
src/neophile/scanner/kustomize.py
src/neophile/scanner/pre_commit.py
src/neophile/scanner/util.py
src/neophile/update/base.py
src/neophile/update/helm.py
src/neophile/update/kustomize.py
src/neophile/update/pre_commit.py
src/neophile/update/python.py
src/neophile/virtualenv.py
tests/util.py

Sphinx can now correctly pick up type information from the type annotations, so switch to the new docstring format that doesn't include redundant types. Take advantage of the opportunity to reword and improve some docstrings and remove some docstrings when the inherited ones would be fine.

DM-39519: Convert to new docstring format

---

src/neophile/analysis/base.py
src/neophile/analysis/helm.py
src/neophile/analysis/kustomize.py
src/neophile/analysis/pre_commit.py
src/neophile/analysis/python.py
src/neophile/cli.py
src/neophile/factory.py
src/neophile/pr.py
src/neophile/processor.py
src/neophile/scanner/base.py
src/neophile/scanner/helm.py
src/neophile/scanner/kustomize.py
src/neophile/scanner/pre_commit.py
tests/analysis/helm_test.py
tests/analysis/kustomize_test.py
tests/analysis/pre_commit_test.py
tests/analysis/python_test.py
tests/pr_test.py
tests/processor_test.py
tests/scanner/helm_test.py
tests/scanner/kustomize_test.py
tests/scanner/pre_commit_test.py

Previously, the Factory object methods took a path to a package to analyze, and the Processor used the Factory to create other objects as needed. This was different than our other packages and a bit of an inversion of the factory pattern.
Instead, change the underlying objects to take the root of the directory to analyze or update as a parameter, make the factory methods take no parameters, and go back to having the factory create the processor object.

DM-39519: Refactor factory and underlying objects

---

.pre-commit-config.yaml
src/neophile/cli.py
src/neophile/factory.py
src/neophile/inventory/github.py
tests/cli_test.py

To more easily allow invoking neophile to manage only a specific type of dependency, add support for listing types of dependencies on the neophile analyze command line.
Report more gidgethub error messages.

DM-39627: Allow specifying types of dependencies to analyze

---

changelog.d/20230605_094239_rra_DM_39519.md
changelog.d/20230612_103114_rra_DM_39627.md
src/neophile/cli.py
src/neophile/processor.py
tests/cli_test.py

Stop printing any output from analyze if there are no detected dependency changes, and omit any dependencies with no detected updates. Exit non-zero if there are dependency changes and neither --update nor --pr were given.

DM-39627: Change analyze output and exit status

---

.github/workflows/ci.yaml
changelog.d/20230612_103114_rra_DM_39627.md
docs/user-guide/usage.rst
src/neophile/cli.py
tests/cli_test.py

On each pull request, check whether dependencies are up-to-date.
Rework the command line so that `neophile check` is suitable for this up-to-date check and the `--update` and `--pr` flags of `neophile analyze` are now implemented by a new `neophile update` command.

DM-39627: Add a GitHub Actions check for dependencies

---

.github/workflows/dependencies.yaml
.pre-commit-config.yaml
changelog.d/20230612_170105_rra_DM_39627.md
docs/user-guide/usage.rst
src/neophile/config.py
src/neophile/pr.py
tests/pr_test.py

Stop embedding the GitHub token in the remote URL for Git repositories and instead assume Git actions will be authenticated externally somehow. Get the GitHub token for GitHub REST API operations from GITHUB_TOKEN instead of NEOPHILE_GITHUB_TOKEN so that it will work from inside GitHub Actions runs with the temporary token for the action.
Add a GitHub Actions job to update pre-commit dependencies using this new facility, and back down a pre-commit dependency so that it will have something to do.

DM-39627: Redo how GitHub tokens are used

---

.github/workflows/dependencies.yaml
changelog.d/20230612_170105_rra_DM_39627.md
src/neophile/config.py

Go back to getting the GitHub token from NEOPHILE_GITHUB_TOKEN, since GitHub Actions creates a temporary secret, not an environment variable. Pass that secret to neophile via the environment in the dependency update workflow.

DM-39627: Revert NEOPHILE_GITHUB_TOKEN change

---

.github/workflows/dependencies.yaml
changelog.d/20230612_174406_rra_DM_39627.md
src/neophile/pr.py
tests/pr_test.py

If NEOPHILE_GITHUB_EMAIL is set, do not try to use the /user endpoint to get the name and email address, and instead use that email address and NEOPHILE_GITHUB_USER (neophile by default) for the name portion. This allows PRs to be created by GitHub Actions, where the /user endpoint is not available.

DM-39627: Redo GitHub actor handling for PRs

---

.github/workflows/dependencies.yaml
changelog.d/20230614_171744_rra_DM_39627.md
docs/documenteer.toml
pyproject.toml
src/neophile/cli.py
src/neophile/config.py
src/neophile/factory.py
src/neophile/inventory/github.py
src/neophile/pr.py
tests/cli_test.py
tests/conftest.py
tests/inventory/github_test.py
tests/pr_test.py
tests/processor_test.py
tests/support/github.py

Rather than using a personal access token, authenticate as a GitHub app, installed into the GitHub repository for which neophile is trying to create a PR. For GitHub tag inventory requests, use an anonymous client, since that should be public information.
This eliminates the last use of github_user as a username, so replace that configuration with commit_name and commit_email and clarify that they're only used for Git commits.
Update the periodic GitHub Action to update pre-commit dependencies to use the new neophile organization-wide GitHub app via organization secrets.

DM-39627: Authenticate as a GitHub app

---

.github/workflows/dependencies.yaml
.github/workflows/periodic.yaml

Send a Slack notification if the periodic dependency update or tests failed.

DM-39627: Add Slack notifications for periodic workflows

---

docs/_rst_epilog.rst
docs/dev/development.rst
docs/dev/index.rst
docs/dev/release.rst

Update the development documentation for tox 4, Ruff, and scriv, and mention that releases are now uploaded to PyPI.

DM-39627: Update development documentation

---

docs/user-guide/github-actions.rst

The introductory comment in the sample periodic GitHub Actions workflow was incorrect.

DM-39627: Fix comment in sample periodic workflow

---

changelog.d/20230707_085835_rra_DM_39919.md
pyproject.toml
src/neophile/pr.py
tests/pr_test.py

Use the GitHub App installation token when pushing Git changes in preparation for creating a PR rather than using the default GitHub Actions token. If the branch was pushed with the GitHub Actions token, further GitHub Actions refuse to run on that branch to avoid creating a loop, but we need GitHub Actions to run so that the dependency update PR can be automerged.

DM-39919: Push Git branches using the installation token

---

.github/workflows/dependencies.yaml
changelog.d/20230707_142506_rra_DM_39919.md
docs/user-guide/github-actions.rst
src/neophile/config.py
src/neophile/pr.py
tests/cli_test.py
tests/pr_test.py
tests/processor_test.py

Remove the commit_name configuration option in favor of a username configuration option. Use it to construct a standard GitHub no-reply email address for that username if no email address was given, by retrieving the GitHub UID for that user and using it to create the standard GitHub email.

DM-39919: Dynamically construct commit email address

---

changelog.d/20230707_153200_rra_DM_39919.md
pyproject.toml

neophile does not currently support Pydantic 2.x, and adding support when Safir doesn't support it is more likely to create than solve problems. Pin Pydantic to 1.x versions for now.

DM-39919: Pin Pydantic to 1.x versions

---

.github/workflows/ci.yaml

Switch to the new version of lsst-sqre/build-and-publish-to-pypi, which uses trusted publishers and environments to authenticate to PyPI instead of using a PyPI token.
Remove some unnecessary names from GitHub actions steps.

DM-39989: Use new lsst-sqre/build-and-publish-to-pypi Action

---

.github/workflows/ci.yaml
.github/workflows/periodic-ci.yaml

Bump the version of lsst-sqre/build-and-publish-to-pypi to v2 everywhere, fixing a previous oversight. Rename periodic.yaml to periodic-ci.yaml to match the templates.

Finish updating PyPI Actions
